import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserMenu from "@/components/UserMenu"; // Import the UserMenu component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="w-full p-4 flex justify-end items-center bg-gray-100 shadow-sm relative z-20">
          {/* UserMenu will be positioned here */}
          <UserMenu />
        </header>
        <main className="flex-grow flex flex-col items-center justify-center relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}
